# Generated by Django 5.1.1 on 2024-09-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeacherInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tea_name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "tea_id",
                    models.CharField(max_length=20, unique=True, verbose_name="工号"),
                ),
                ("tea_password", models.CharField(max_length=128, verbose_name="密码")),
            ],
            options={
                "verbose_name": "教师信息",
                "verbose_name_plural": "教师信息",
            },
        ),
    ]
