# Generated by Django 5.1.1 on 2024-10-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_teacher', '0002_remove_teacherinformation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinformation',
            name='gender',
        ),
        migrations.AddField(
            model_name='teacherinformation',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
