<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-09-24 12:46

=======
# Generated by Django 5.1.1 on 2024-10-14 08:59

import django.db.models.deletion
from django.conf import settings
>>>>>>> 83f1edfc5ffa8e9f876eb602fbd78e4443d636dc
from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "stu_id",
                    models.CharField(max_length=20, unique=True, verbose_name="学号"),
                ),
                ("stu_password", models.CharField(max_length=128, verbose_name="密码")),
                ("major", models.CharField(max_length=100, verbose_name="专业")),
            ],
            options={
                "verbose_name": "学生信息",
                "verbose_name_plural": "学生信息",
            },
=======

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
>>>>>>> 83f1edfc5ffa8e9f876eb602fbd78e4443d636dc
        ),
    ]
