<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-09-22 09:47
=======
# Generated by Django 5.1.1 on 2024-09-21 13:52
>>>>>>> 83f1edfc5ffa8e9f876eb602fbd78e4443d636dc

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('stu_name', models.CharField(max_length=50)),
                ('stu_id', models.CharField(max_length=20, unique=True)),
                ('stu_password', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=100)),
=======
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),

>>>>>>> 83f1edfc5ffa8e9f876eb602fbd78e4443d636dc
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('tea_name', models.CharField(max_length=50)),
                ('tea_id', models.CharField(max_length=20, unique=True)),
                ('tea_password', models.CharField(max_length=50)),
=======
                ('name', models.CharField(max_length=100)),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
>>>>>>> 83f1edfc5ffa8e9f876eb602fbd78e4443d636dc
            ],
        ),
    ]
