# Generated by Django 5.1.1 on 2024-10-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_studentinfo_email_teacherinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='teacher_id',
            field=models.CharField(max_length=20),
        ),
    ]
