"""
<<<<<<< HEAD
Django settings for NetSecLab project.
=======
Django settings for myproject project.
>>>>>>> 83f1edfc5ffa8e9f876eb602fbd78e4443d636dc

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

<<<<<<< HEAD
from django.template import Engine

=======
>>>>>>> 83f1edfc5ffa8e9f876eb602fbd78e4443d636dc
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
<<<<<<< HEAD
SECRET_KEY = "django-insecure-2&6v9)!58=)=-e0m-emp!afz0$w1!on=k2jtij$jni)va%pn%l"
=======
SECRET_KEY = 'django-insecure-p4n_(3e&v(fi6ioxmh$^tb^a0)y!2)nvr#4kc8ppcbq!^ga+fl'
>>>>>>> 83f1edfc5ffa8e9f876eb602fbd78e4443d636dc

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
<<<<<<< HEAD
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "More_apps.authen",
    "More_apps.competition_student",
    "More_apps.competition_teacher",
    "More_apps.competition_announcement",
    "More_apps.guide",
    "More_apps.lab",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "NetSecLab.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'More_apps', 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
=======
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'More_apps.authen',
    "More_apps.competition_student",
    "More_apps.competition_teacher",
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CSRF_TRUSTED_ORIGINS = ['http://localhost:8080']
CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'NetSecLab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'More_apps', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
>>>>>>> 83f1edfc5ffa8e9f876eb602fbd78e4443d636dc
            ],
        },
    },
]

<<<<<<< HEAD
WSGI_APPLICATION = "NetSecLab.wsgi.application"
=======
WSGI_APPLICATION = 'NetSecLab.wsgi.application'
>>>>>>> 83f1edfc5ffa8e9f876eb602fbd78e4443d636dc


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
<<<<<<< HEAD
    "default": {
        "ENGINE":"django.db.backends.mysql",
        "NAME": "user",
        "USER": "root",
        "PASSWORD": "000000",
        "HOST": "127.0.0.1",
        "PORT": "3306",
=======
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'test',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'POST': 3306,
        'OPTIONS':{'isolation_level':None}
>>>>>>> 83f1edfc5ffa8e9f876eb602fbd78e4443d636dc
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
<<<<<<< HEAD
        "NAME": "django.contrib.authen.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.authen.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.authen.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.authen.password_validation.NumericPasswordValidator",
=======
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
>>>>>>> 83f1edfc5ffa8e9f876eb602fbd78e4443d636dc
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

<<<<<<< HEAD
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"
=======
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
>>>>>>> 83f1edfc5ffa8e9f876eb602fbd78e4443d636dc

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

<<<<<<< HEAD
STATIC_URL = "static/"
=======
STATIC_URL = 'static/'
>>>>>>> 83f1edfc5ffa8e9f876eb602fbd78e4443d636dc

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

<<<<<<< HEAD
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
=======
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_ROOT = r'C:\Users\23991\Desktop\upload'
MEDIA_URL = '/media/'
>>>>>>> 83f1edfc5ffa8e9f876eb602fbd78e4443d636dc
